<img src="The-Northcap-University-NCU-logo.png">


## Static graph (TensorFlow 1.x) vs Eager execution (TensorFlow 2.0)

![alt text](https://www.tensorflow.org/images/tensors_flowing.gif)
*Image take from: https://www.tensorflow.org/guide/graphs*


## TensorFlow 1.X




### Installing TensorFlow 1.X



In [1]:
!pip install tensorflow-gpu==1.13.1

     |████████████████████████████████| 345.2MB 48kB/s 
     |████████████████████████████████| 368kB 44.6MB/s 
     |████████████████████████████████| 3.2MB 42.1MB/s 
ERROR: tensorflow 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 1.13.1 which is incompatible.
ERROR: tensorflow 2.2.0 has requirement tensorflow-estimator<2.3.0,>=2.2.0, but you'll have tensorflow-estimator 1.13.0 which is incompatible.
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Found existing installation: tensorboard 2.2.1
    Uninstalling tensorboard-2.2.1:
      Successfully uninstalled tensorboard-2.2.1


In [2]:
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

In [3]:
tf.__version__

'1.13.1'

### Variables and constants in TF 1.x

#### Variables

In [4]:
#Initialize normal Variable in tf 1.x
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [5]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [6]:
#Getting shape of the variable
variable.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [7]:
#Performing addition operation on the tensor produces another tf.Tensor object
variable + 2

<tf.Tensor 'add:0' shape=(2, 2) dtype=int32>

In [8]:
#If a session is not initialized we cannot access values in the Variable/Tensor
variable.eval()

ValueError: ignored

In [9]:
#Able to slice a variable, but we are still not able to retrive values from it
variable[:1]

<tf.Tensor 'strided_slice:0' shape=(1, 2) dtype=int32>

#### Getting values from variables

In [0]:
#Initialize session
session = tf.Session()

In [0]:
#Initialize ALL variables for the session
session.run(tf.global_variables_initializer())

In [12]:
#Run the eval method on the evironment with provided session to retrive values from it
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

#### Constants/Tensors

In [0]:
#Define a TensorFlow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

In [14]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [15]:
#We are still not able to get the real value without defining a session
tensor.eval()

ValueError: ignored

#### Getting values from constants

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
#Fatching the tensor from the tensor graph/session
tensor_value = session.run(tensor)

In [19]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [5]:
!pip install tensorflow==2.2.0

     |████████████████████████████████| 516.2MB 33kB/s 
  Using cached https://files.pythonhosted.org/packages/1d/74/0a6fcb206dcc72a6da9a62dd81784bfdbff5fedb099982861dc2219014fb/tensorboard-2.2.2-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/a4/f5/926ae53d6a226ec0fda5208e0e581cffed895ccc89e36ba76a8e60895b78/tensorflow_estimator-2.2.0-py2.py3-none-any.whl
ERROR: tensorflow-gpu 1.13.1 has requirement tensorboard<1.14.0,>=1.13.0, but you'll have tensorboard 2.2.2 which is incompatible.
ERROR: tensorflow-gpu 1.13.1 has requirement tensorflow-estimator<1.14.0rc0,>=1.13.0, but you'll have tensorflow-estimator 2.2.0 which is incompatible.
  Found existing installation: tensorboard 2.0.2
    Uninstalling tensorboard-2.0.2:
      Successfully uninstalled tensorboard-2.0.2
  Found existing installation: gast 0.2.2
    Uninstalling gast-0.2.2:
      Successfully uninstalled gast-0.2.2
  Found existing installation: tensorflow-estimator 2.0.1
    Uninstalling tensorflow-e

In [6]:
%tensorflow_version 2.2.0

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.2.0`. This will be interpreted as: `2.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.


In [0]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.2.0'

### Constants/Tensors

In [0]:
#Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [4]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [5]:
#Getting shape of a tensor
tensor_20.shape

TensorShape([2, 2])

### Getting values from constants

In [6]:
#Getting values straight from a TensorFlow constant to numpy - withut sesion
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
#We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [9]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Operations with constants/tensors

In [10]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Addition between scalar and tensor

In [11]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplication between scalar and tensor

In [12]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [13]:
#Squaring all numbers in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [14]:
#Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [15]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Operations with variables

In [16]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting raw value from the variable

In [17]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing specific value in the TensorFlow variable

In [18]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [19]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Strings in TensorFlow 2.0

In [20]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [21]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [22]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [24]:
#How to iterate through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


### Handling Devices in TensorFlow 2.0

#### CPU

In [0]:
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [6]:
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'

#### GPU

In [7]:
if tf.config.list_physical_devices('CPU'):
  tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
  print(tf_string_array.device)
  print(tf_string_array)

/job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([b'TensorFlow' b'Deep Learning' b'AI'], shape=(3,), dtype=string)


In [0]:
if tf.config.list_physical_devices('GPU'):
  
  tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
  
  print(tf_string_array.device)